In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
food = pd.read_csv('1662574418893344.csv')
ratings = pd.read_csv('ratings.csv')

In [3]:
food.head()

Food_ID                  Name        C_Type  Veg_Non  \
0        1   summer squash salad  Healthy Food      veg   
1        2  chicken minced salad  Healthy Food  non-veg   
2        3  sweet chilli almonds         Snack      veg   
3        4       tricolour salad  Healthy Food      veg   
4        5        christmas cake       Dessert      veg   

                                            Describe  
0  white balsamic vinegar, lemon juice, lemon rin...  
1  olive oil, chicken mince, garlic (minced), oni...  
2  almonds whole, egg white, curry leaves, salt, ...  
3  vinegar, honey/sugar, soy sauce, salt, garlic ...  
4  christmas dry fruits (pre-soaked), orange zest...

In [4]:
ratings.head()

User_ID  Food_ID  Rating
0      1.0     88.0     4.0
1      1.0     46.0     3.0
2      1.0     24.0     5.0
3      1.0     25.0     4.0
4      2.0     49.0     1.0

In [6]:
food.isna().sum()

Food_ID     0
Name        0
C_Type      0
Veg_Non     0
Describe    0
dtype: int64

In [7]:
ratings.isna().sum()

User_ID    1
Food_ID    1
Rating     1
dtype: int64

In [8]:
ratings.dropna(inplace = True)

In [9]:
ratings.isna().sum()

User_ID    0
Food_ID    0
Rating     0
dtype: int64

In [11]:
food.shape

(400, 5)

In [12]:
ratings.shape


(511, 3)

In [13]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Food_ID   400 non-null    int64 
 1   Name      400 non-null    object
 2   C_Type    400 non-null    object
 3   Veg_Non   400 non-null    object
 4   Describe  400 non-null    object
dtypes: int64(1), object(4)
memory usage: 15.8+ KB


In [14]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 511 entries, 0 to 510
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   User_ID  511 non-null    float64
 1   Food_ID  511 non-null    float64
 2   Rating   511 non-null    float64
dtypes: float64(3)
memory usage: 16.0 KB


In [17]:
ratings[['User_ID' ,'Food_ID']] =ratings[['User_ID' ,'Food_ID']].astype('int64')

In [18]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 511 entries, 0 to 510
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   User_ID  511 non-null    int64  
 1   Food_ID  511 non-null    int64  
 2   Rating   511 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 16.0 KB


In [20]:
ratings.dropna(axis=0 ,inplace=True)

In [21]:
ratings.duplicated().sum()

0

In [23]:
food_rating = pd.merge(food ,ratings ,on='Food_ID')
food_rating.head()

Food_ID                  Name        C_Type  Veg_Non  \
0        1   summer squash salad  Healthy Food      veg   
1        1   summer squash salad  Healthy Food      veg   
2        2  chicken minced salad  Healthy Food  non-veg   
3        2  chicken minced salad  Healthy Food  non-veg   
4        2  chicken minced salad  Healthy Food  non-veg   

                                            Describe  User_ID  Rating  
0  white balsamic vinegar, lemon juice, lemon rin...       49     5.0  
1  white balsamic vinegar, lemon juice, lemon rin...       71    10.0  
2  olive oil, chicken mince, garlic (minced), oni...        9     3.0  
3  olive oil, chicken mince, garlic (minced), oni...       22     5.0  
4  olive oil, chicken mince, garlic (minced), oni...       39    10.0

In [25]:
food_rating.shape

(511, 7)

In [28]:
food_rating.duplicated().sum()

0

In [30]:
food_rating.isna().sum()

Food_ID     0
Name        0
C_Type      0
Veg_Non     0
Describe    0
User_ID     0
Rating      0
dtype: int64

In [31]:
food_rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 511 entries, 0 to 510
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Food_ID   511 non-null    int64  
 1   Name      511 non-null    object 
 2   C_Type    511 non-null    object 
 3   Veg_Non   511 non-null    object 
 4   Describe  511 non-null    object 
 5   User_ID   511 non-null    int64  
 6   Rating    511 non-null    float64
dtypes: float64(1), int64(2), object(4)
memory usage: 28.1+ KB


In [32]:
# 3. Convert C_Type and Veg_Non to numerical representations
food_rating["C_Type"] = food_rating["C_Type"].astype("category").cat.codes
food_rating["Veg_Non"] = food_rating["Veg_Non"].astype("category").cat.codes

In [33]:
food_rating.head()

Food_ID                  Name  C_Type  Veg_Non  \
0        1   summer squash salad       4        1   
1        1   summer squash salad       4        1   
2        2  chicken minced salad       4        0   
3        2  chicken minced salad       4        0   
4        2  chicken minced salad       4        0   

                                            Describe  User_ID  Rating  
0  white balsamic vinegar, lemon juice, lemon rin...       49     5.0  
1  white balsamic vinegar, lemon juice, lemon rin...       71    10.0  
2  olive oil, chicken mince, garlic (minced), oni...        9     3.0  
3  olive oil, chicken mince, garlic (minced), oni...       22     5.0  
4  olive oil, chicken mince, garlic (minced), oni...       39    10.0

In [34]:
food_rating['C_Type'].unique()

array([ 4,  9,  2,  7,  5,  3,  8,  6,  1,  0, 10], dtype=int8)

In [35]:
food_rating['Veg_Non'].unique()

array([1, 0], dtype=int8)

In [36]:
# 4. Map user ids and food ids to numerical ids starting from 0
user_ids = food_rating["User_ID"].unique()
food_ids = food_rating["Food_ID"].unique()


In [37]:
print(user_ids)

[ 49  71   9  22  39  77  89  41  90  28  73  88  94  98  43  92  17  48
  63  70   5  82  19  62  16  45  34  75  21  55   4  26  35  79  36  67
  14  18  64  84  93  47  50  97   7  78  80   6  53  61  68  99  24  69
  76   1  86 100  54  23  95  15  87  32   2  57  29  11  12  83  38  59
  10  52  74   3  20  85  65  96  30  51  27  25  46  81  13  31  42  58
  66  37   8  60  40  91  33  72  44  56]


In [38]:
print(food_ids)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [39]:
user_id_map = {uid: i for i, uid in enumerate(user_ids)}
food_id_map = {fid: i for i, fid in enumerate(food_ids)}

In [40]:
print(user_id_map)

{49: 0, 71: 1, 9: 2, 22: 3, 39: 4, 77: 5, 89: 6, 41: 7, 90: 8, 28: 9, 73: 10, 88: 11, 94: 12, 98: 13, 43: 14, 92: 15, 17: 16, 48: 17, 63: 18, 70: 19, 5: 20, 82: 21, 19: 22, 62: 23, 16: 24, 45: 25, 34: 26, 75: 27, 21: 28, 55: 29, 4: 30, 26: 31, 35: 32, 79: 33, 36: 34, 67: 35, 14: 36, 18: 37, 64: 38, 84: 39, 93: 40, 47: 41, 50: 42, 97: 43, 7: 44, 78: 45, 80: 46, 6: 47, 53: 48, 61: 49, 68: 50, 99: 51, 24: 52, 69: 53, 76: 54, 1: 55, 86: 56, 100: 57, 54: 58, 23: 59, 95: 60, 15: 61, 87: 62, 32: 63, 2: 64, 57: 65, 29: 66, 11: 67, 12: 68, 83: 69, 38: 70, 59: 71, 10: 72, 52: 73, 74: 74, 3: 75, 20: 76, 85: 77, 65: 78, 96: 79, 30: 80, 51: 81, 27: 82, 25: 83, 46: 84, 81: 85, 13: 86, 31: 87, 42: 88, 58: 89, 66: 90, 37: 91, 8: 92, 60: 93, 40: 94, 91: 95, 33: 96, 72: 97, 44: 98, 56: 99}


In [41]:
print(food_id_map)

{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11, 13: 12, 14: 13, 15: 14, 16: 15, 17: 16, 18: 17, 19: 18, 20: 19, 21: 20, 22: 21, 23: 22, 24: 23, 25: 24, 26: 25, 27: 26, 28: 27, 29: 28, 30: 29, 31: 30, 32: 31, 33: 32, 34: 33, 35: 34, 36: 35, 37: 36, 38: 37, 39: 38, 40: 39, 41: 40, 42: 41, 43: 42, 44: 43, 45: 44, 46: 45, 47: 46, 48: 47, 49: 48, 50: 49, 51: 50, 52: 51, 53: 52, 54: 53, 55: 54, 56: 55, 57: 56, 58: 57, 59: 58, 60: 59, 61: 60, 62: 61, 63: 62, 64: 63, 65: 64, 66: 65, 67: 66, 68: 67, 69: 68, 70: 69, 71: 70, 72: 71, 73: 72, 74: 73, 75: 74, 76: 75, 77: 76, 78: 77, 79: 78, 80: 79, 81: 80, 82: 81, 83: 82, 84: 83, 85: 84, 86: 85, 87: 86, 88: 87, 89: 88, 90: 89, 91: 90, 92: 91, 93: 92, 94: 93, 95: 94, 96: 95, 97: 96, 98: 97, 99: 98, 100: 99, 101: 100, 102: 101, 103: 102, 104: 103, 105: 104, 106: 105, 107: 106, 108: 107, 109: 108, 110: 109, 111: 110, 112: 111, 113: 112, 114: 113, 115: 114, 116: 115, 117: 116, 118: 117, 119: 118, 120: 119, 121: 120, 122: 12

In [42]:
food_rating["User_ID"] = food_rating["User_ID"].map(user_id_map)
food_rating["Food_ID"] = food_rating["Food_ID"].map(food_id_map)

In [44]:
food_rating.head()

Food_ID                  Name  C_Type  Veg_Non  \
0        0   summer squash salad       4        1   
1        0   summer squash salad       4        1   
2        1  chicken minced salad       4        0   
3        1  chicken minced salad       4        0   
4        1  chicken minced salad       4        0   

                                            Describe  User_ID  Rating  
0  white balsamic vinegar, lemon juice, lemon rin...        0     5.0  
1  white balsamic vinegar, lemon juice, lemon rin...        1    10.0  
2  olive oil, chicken mince, garlic (minced), oni...        2     3.0  
3  olive oil, chicken mince, garlic (minced), oni...        3     5.0  
4  olive oil, chicken mince, garlic (minced), oni...        4    10.0

In [45]:
# 5. Change rating to float if needed:
food_rating["Rating"] = food_rating["Rating"].astype(float)


In [48]:
food_rating['Rating'].dtype

dtype('float64')

In [49]:
# 6.  Data for model (Implicit feedback: interactions)
ratings = tf.data.Dataset.from_tensor_slices(
    {
        "user_id": food_rating["User_ID"].values,
        "item_id": food_rating["Food_ID"].values,
        "rating": food_rating["Rating"].values, # added rating column to dataset
    }
)

In [52]:
print(ratings)

<_TensorSliceDataset element_spec={'user_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'item_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'rating': TensorSpec(shape=(), dtype=tf.float64, name=None)}>


In [53]:
# Convert the data type of values in the dictionary to tf.int64 for model training
ratings = ratings.map(lambda x: {
  "user_id": tf.cast(x['user_id'], tf.int64),
  "item_id": tf.cast(x['item_id'], tf.int64),
  "rating": tf.cast(x['rating'], tf.float32)
})

In [54]:
print(ratings)

<_MapDataset element_spec={'user_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'item_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'rating': TensorSpec(shape=(), dtype=tf.float32, name=None)}>


In [56]:
# Randomly split into training and testing
cached_ratings = ratings.shuffle(len(food_rating)).cache()

In [57]:
# Set split ratio to 80:20
train_size = int(0.8 * len(food_rating))
test_size = len(food_rating) - train_size

In [58]:
train_ratings = cached_ratings.take(train_size)
test_ratings = cached_ratings.skip(train_size).take(test_size)

In [59]:
# Check if the train and test data is correct by printing it
for x in train_ratings.take(1):
  print(f"Train dataset example: {x}")

for x in test_ratings.take(1):
  print(f"Test dataset example: {x}")

Train dataset example: {'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=15>, 'item_id': <tf.Tensor: shape=(), dtype=int64, numpy=52>, 'rating': <tf.Tensor: shape=(), dtype=float32, numpy=5.0>}
Test dataset example: {'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=57>, 'item_id': <tf.Tensor: shape=(), dtype=int64, numpy=23>, 'rating': <tf.Tensor: shape=(), dtype=float32, numpy=10.0>}


In [60]:
# --- Model Building ---
embedding_dimension = 32  # Define embedding dimension

class UserModel(tf.keras.Model):
  def __init__(self, embedding_dimension, unique_user_ids):
    super().__init__()

    self.embedding = tf.keras.Sequential([
      tf.keras.layers.Embedding(unique_user_ids, embedding_dimension),
    ])

  def call(self, user_ids):
    return self.embedding(user_ids)

In [63]:
class ItemModel(tf.keras.Model):
    def __init__(self, embedding_dimension, unique_item_ids):
        super().__init__()

        self.embedding = tf.keras.Sequential([
          tf.keras.layers.Embedding(unique_item_ids, embedding_dimension),
        ])

    def call(self, item_ids):
        return self.embedding(item_ids)


In [64]:
# !pip install tensorflow-recommenders

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 2.2 MB/s eta 0:00:00


In [66]:
import tensorflow_recommenders as tfrs

In [74]:
import tensorflow as tf

class RecommendationModel(tfrs.models.Model):

  def __init__(self, embedding_dimension, unique_user_ids, unique_item_ids):
    super().__init__()
    self.user_model = UserModel(embedding_dimension, unique_user_ids)
    self.item_model = ItemModel(embedding_dimension, unique_item_ids)
    self.task = tfrs.tasks.Ranking(
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[tf.keras.metrics.RootMeanSquaredError()],
    )

  def call(self, features):
    user_embeddings = self.user_model(features["user_id"])
    item_embeddings = self.item_model(features["item_id"])
    return user_embeddings, item_embeddings

  def compute_loss(self, features, training=False):
    # Create a copy of the features dictionary to avoid modification
    features = features.copy()
    ratings = features.pop("rating")

    user_embeddings, item_embeddings = self(features)
    return self.task(
        labels=ratings,
        predictions=tf.reduce_sum(tf.multiply(user_embeddings, item_embeddings), axis=1),
    )

In [75]:
# Find the number of unique users and items
unique_user_ids = len(user_ids)
unique_item_ids = len(food_ids)


In [76]:
print(unique_user_ids)
print(unique_item_ids)

100
309


In [77]:
# Instantiate the model
model = RecommendationModel(embedding_dimension, unique_user_ids, unique_item_ids)

In [78]:
# --- Training the model ---
optimizer = tf.keras.optimizers.Adam(0.001)  # Set learning rate
model.compile(optimizer=optimizer)

In [79]:
# Train the model
model.fit(train_ratings.batch(16), epochs=100, verbose = 1)

Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py:391: UserWarning: `build()` was called on layer 'recommendation_model_1', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(


26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36.1975 - regularization_loss: 0.0000e+00 - root_mean_squared_error: 6.2312 - total_loss: 36.1975
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.6173 - regularization_loss: 0.0000e+00 - root_mean_squared_error: 6.2115 - total_loss: 37.6173  
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.7705 - regularization_loss: 0.0000e+00 - root_mean_squared_error: 5.8914 - total_loss: 36.7705
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.8141 - regularization_loss: 0.0000e+00 - root_mean_squared_error: 6.2843 - total_loss: 37.8141 
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.8154 - regularization_loss: 0.0000e+00 - root_mean_squared_error: 6.1731 - total_loss: 37.8154 
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36.9261 - regularization_loss: 0.0000e+00 - root_mean_squared_error: 6.1364 - total_loss: 36.9261 
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.068

In [80]:
# Evaluate the model
evaluation = model.evaluate(test_ratings.batch(128), return_dict = True, verbose = 1)
print(evaluation)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step - loss: 0.1267 - regularization_loss: 0.0000e+00 - root_mean_squared_error: 0.3560 - total_loss: 0.1267
{'loss': 0.12673985958099365, 'regularization_loss': 0.0, 'root_mean_squared_error': 0.3560054302215576, 'total_loss': 0.12673985958099365}


In [81]:
# --- Model Conversion to TFLite ---

# Helper function to get input specifications for the TFLite converter
def get_input_spec(dataset):
  """Helper to get the input specification to convert the model to TFLite.

  Args:
    dataset: Dataset from which to grab input specs

  Returns:
    Input specifications for the tflite converter.
  """
  input_spec = tf.nest.map_structure(
    lambda tensor: tf.TensorSpec(shape=tensor.shape, dtype=tensor.dtype),
    dataset.element_spec)
  return input_spec

In [82]:
# Convert model to tflite
tflite_input_spec = get_input_spec(train_ratings.batch(1).take(1)) # take 1 batch to get the input spec
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]  # Needed to use the Keras Lambda layer
converter.input_spec = tflite_input_spec # Input spec
tflite_model = converter.convert()

Saved artifact at '/tmp/tmpvodb49uv'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): Dict[['user_id', TensorSpec(shape=(None,), dtype=tf.float32, name='user_id')], ['item_id', TensorSpec(shape=(None,), dtype=tf.float32, name='item_id')]]
Output Type:
  Tuple[TensorSpec(shape=(None, 32), dtype=tf.float32, name=None), TensorSpec(shape=(None, 32), dtype=tf.float32, name=None)]
Captures:
  133737501533072: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133737501534800: TensorSpec(shape=(), dtype=tf.resource, name=None)


In [83]:
# Save the converted model
with open('food_recommendation_model.tflite', 'wb') as f:
  f.write(tflite_model)
print("Tensorflow Lite Model Converted and Saved")

Tensorflow Lite Model Converted and Saved


In [85]:
food_rating.head()

Food_ID                  Name  C_Type  Veg_Non  \
0        0   summer squash salad       4        1   
1        0   summer squash salad       4        1   
2        1  chicken minced salad       4        0   
3        1  chicken minced salad       4        0   
4        1  chicken minced salad       4        0   

                                            Describe  User_ID  Rating  
0  white balsamic vinegar, lemon juice, lemon rin...        0     5.0  
1  white balsamic vinegar, lemon juice, lemon rin...        1    10.0  
2  olive oil, chicken mince, garlic (minced), oni...        2     3.0  
3  olive oil, chicken mince, garlic (minced), oni...        3     5.0  
4  olive oil, chicken mince, garlic (minced), oni...        4    10.0

In [89]:
# food_rating['User_ID']